#! /bin/sh
picom &
sxhkd &
$HOME/.config/polybar/launch.sh &

if [ -x $HOME/.local/share/scripts/bspwm_dual_monitor ];then
    bspwm_dual_monitor
fi &

# -- ///// Autostart ///// -- #

# Notifications
dunst --config /home/waffelo/.config/dunst/dunstrc &

# Compositor
picom --experimental-backends --backend glx --xrender-sync-fence &

# Wallpaper
feh --bg-tile ~/Pictures/Wallpapers/circuit\ pattern.png &
#nitrogen --restore &

# Discord RPC for websites
# s premid &

# -- ///// Stuff ///// -- #

bspc monitor LVDS-1 -d I II III IV V VI VII  
bspc monitor VGA-1 -d I II III IV V VI VII  

#bspc monitor -d '| Communication |' '| Web |' '| Dev |' '| School |' '| System |'

bspc config focused_border_color "#5c7c96"
bspc config inactive_border_color "#1f1d24"
#bspc config active_border_color  "#5f819d"
bspc config border_width 	 2
bspc config window_gap 		 8
bspc config click_to_focus button1

# -- ///// Rules ///// -- #

bspc rule -a Zathura state=tiled
bspc rule -a emacs state=tiled
